### ISSUE TITLE
Page management > page settings > upload image

### ISSUE THREAD

**Issue by informa** [tangentlabs/django-oscar-fancypages#101]
Uploading an image as part of a fancypage category through:
- dashboard/fancypages > page settings

Doesn't save the image on page save.

![screen shot 2013-08-14 at 9 30 22 am](https://f.cloud.github.com/assets/726265/958853/650bddee-0470-11e3-8017-1b4dd60fa90b.png)

**Comment by roadsideseb** [comment]
Fixed in d3041511601d4db6b6cca6e182713adc3e91d5cf
