### ISSUE TITLE
Moving content block after adding doesnt work

### ISSUE THREAD

**Issue by garthus** [tangentlabs/django-oscar-fancypages#13]
When you create a content block at the bottom of the page, then edit the content and move the block to the top before saving, after saving it moves back to the bottom.

**Comment by garthus** [comment]
What seems to happen at the moment:

1) Add a content block, eg Text
2) Edit the text but dont save anything
3) Move the block to further up the page
4) The block moves, but the text reverts to Intert your text here

**Comment by roadsideseb** [comment]
The reason for this behaviour is that moving the block around wil (have to) cause a refresh of the page as it is submitted to the backend. If the text/content is not saved it will be lost.

 One way around this would be to have a pop-up notify the user that they have unsaved content when they are trying to move the widget and asked them to save or discard the changes. Would that be a feasible solution?
