### ISSUE TITLE
Adding H1 to the Rich Test Editor

### ISSUE THREAD

**Issue by garthus** [tangentlabs/django-oscar-fancypages#2]
When you are editing rich text, it would be great to have the ability to add:

H1
H2
H3

Probably best to use one dropdown for all

We can also remove the <br>

**Comment by roadsideseb** [comment]
I added the dropdown but it still needs some FE-love :)

**Comment by roadsideseb** [comment]
Oh, and what do you want removed? Half of the sentence is missing up there...

**Comment by garthus** [comment]
Awesome - need to remove the:

<   BR   >

**Comment by roadsideseb** [comment]
Done and built to glitterbox :sparkles:

**Comment by informa** [comment]
Fixed a conflict and re-added the version I added on Sat.  only reason is that we are using a navbar - instead of a button group to display the buttons now.
