### ISSUE TITLE
Add to Page settings

### ISSUE THREAD

**Issue by garthus** [tangentlabs/django-oscar-fancypages#5]
We should add a few items to the page settings:

Meta Description
Meta Keywords

Shown in the Wireframe here:

http://share.axure.com/HIM81D/Oscar___Fancy_Pages__editing_.html

Can we also add in the URL to the page which people might be able to edit (the slug)

And a View on Site button to view the page

**Comment by roadsideseb** [comment]
I hope you don't mind that I removed the password but if we decide to make fancypages publicly available at some point we might not remember to remove that.

**Comment by garthus** [comment]
No problem on the password
