### ISSUE TITLE
Editing a page is unclear

### ISSUE THREAD

**Issue by codeinthehole** [tangentlabs/django-oscar-fancypages#62]
I created a new page in my local sandbox and went to customise it but I'm unsure how to do it.  Here's a screengrab:
![image](https://f.cloud.github.com/assets/80975/180090/43ab7ac4-7c21-11e2-8088-08a8093d7380.png)
- The left-hand form is unlabelled which makes it quite confusing
- How to I add content?  I can't see a button anywhere

**Comment by roadsideseb** [comment]
This seems to be caused by some CSS/JS inclusion errors. This shouldn't be an issue in the current master branch. Would you mind double-checking this using the most recent master and let me know if you are still having problem?

**Comment by codeinthehole** [comment]
Yes, that does seem to be fixed.  The whole editing paradigm seems to have changed to do "in-page" editing rather than within the dashboard.
