### ISSUE TITLE
Dropdown not visible for child page

### ISSUE THREAD

**Issue by codeinthehole** [tangentlabs/django-oscar-fancypages#63]
The admin dropdown is not visible for a child page in the dashboard list view:
![image](https://f.cloud.github.com/assets/80975/180134/a7987eae-7c23-11e2-9f61-8497f8e2c123.png)

**Comment by roadsideseb** [comment]
This seems to be fixed within the latest versions of FP and OFP. Please re-open this ticket if you still have issues.
