### ISSUE TITLE
Not possible to add anchor tag

### ISSUE THREAD

**Issue by Tilley** [tangentlabs/django-oscar-fancypages#96]
The parser rules for fancypages strip id and name attributes from `<a>` elements, making it impossible to create an anchor tag

**Comment by roadsideseb** [comment]
I am not sure what you mean by parser rules. Where exactly is this happening?

**Comment by Tilley** [comment]
Sorry, "parser rules for fancypages" was supposed to say "parser rules for wysihtml5".

https://github.com/tangentlabs/django-oscar-fancypages/blob/master/fancypages/static/fancypages/js/wysihtml5/advanced.js#L181-L184

From what I can tell with wysihtml5, if an attribute is not listed as a "check_attribute" it is stripped from the html in the editor

**Comment by roadsideseb** [comment]
This is fixed in [django-fancypages](https://github.com/tangentlabs/django-fancypages) via commit [d8bf4bf](https://github.com/tangentlabs/django-fancypages/commit/d8bf4bf41b04d43d3ae78a2b06ea3fa150221fb1).
